repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml  # Attempts to load all yaml files to verify syntax.
        -   id: check-json  # Attempts to load all json files to verify syntax.
        -   id: check-xml  # Attempts to load all xml files to verify syntax.
        -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
        -   id: trailing-whitespace # Trims trailing whitespace.
            with:
              args: [--markdown-linebreak-ext=md]

  -   repo: https://github.com/maltzj/google-style-precommit-hook
      rev: 95c2f56
      hooks:
          - id: google-style-java # Uses google java format: https://github.com/google/google-java-format
