repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

  -   repo: https://github.com/maltzj/google-style-precommit-hook
      rev: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
      hooks:
          - id: google-style-java
