name: Format Java Code as per Google Java Format program

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # v2 minimum required

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
