name: reusable-workflow-template-to-run-tests

on:
  workflow_call:
    inputs:
      tags-of-tests-to-include:
        required: true
        type: string

      tags-of-tests-to-exclude:
        required: false
        type: string
        default: "flaky,failing"

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Test with Maven
        run: mvn -DexcludedGroups=${{ inputs.tags-of-tests-to-exclude }} -Dgroups=${{ inputs.tags-of-tests-to-include }} -B package --file pom.xml
