# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
<<<<<<<< HEAD:.github/workflows/test-the-tester-on-merge-to-main.yml
  push:
========
  pull_request:
>>>>>>>> main:.github/workflows/test-the-tester-on-pull-request.yml
    branches: [ main ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: Test with Maven
<<<<<<<< HEAD:.github/workflows/test-the-tester-on-merge-to-main.yml
      run: mvn -DexcludedGroups="flaky | failing"  -Dgroups="" -B package --file pom.xml
========
      run: mvn -DexcludedGroups="flaky | failing" -Dgroups=smoke -B package --file pom.xml
>>>>>>>> main:.github/workflows/test-the-tester-on-pull-request.yml
