name: deployment-completed-event-recevied-to-trigger-tests
on:
  repository_dispatch:
    types: [deployment-completed]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
